import Anthropic from '@anthropic-ai/sdk';

/**
 * Serverless coaching endpoint. Runs on Vercel (Node runtime) so the
 * ANTHROPIC_API_KEY stays server-side and never reaches the browser bundle.
 * The frontend POSTs the day's derived numbers; we return one short,
 * specific coaching line generated by Claude Haiku.
 */

type CoachRequest = {
  goal?: 'deficit' | 'surplus' | 'maintenance';
  caloriesLogged?: number;
  calorieTarget?: number;
  proteinLogged?: number;
  proteinTarget?: number | null;
  carbsLogged?: number;
  fatLogged?: number;
  steps?: number | null;
  waterMl?: number | null;
  latestWeight?: number | null;
  weightTrend?: string | null;
  streak?: number;
  mealCount?: number;
};

const SYSTEM_PROMPT = `You are a concise, encouraging fitness and nutrition coach inside a personal tracker app.
You receive the user's numbers for today and give ONE short, specific piece of guidance (2-3 sentences max, no more than ~45 words).
Rules:
- Be concrete: reference the actual numbers (calories left, protein gap, streak, weight trend).
- Prioritise the single most useful nudge for right now.
- Warm but not gushing. No emoji spam (at most one). No markdown, no headings, no lists — plain sentences only.
- If they're on track, say so plainly and give a small next step.
- Never invent numbers you weren't given. If data is missing, coach around what you have.`;

function buildUserMessage(d: CoachRequest): string {
  const lines: string[] = [];
  if (d.goal) lines.push(`Goal: ${d.goal}`);
  if (d.calorieTarget != null) {
    const left = Math.max(0, Math.round(d.calorieTarget - (d.caloriesLogged ?? 0)));
    lines.push(`Calories: ${Math.round(d.caloriesLogged ?? 0)} logged of ${Math.round(d.calorieTarget)} target (${left} left)`);
  }
  if (d.proteinTarget != null) {
    const gap = Math.max(0, Math.round(d.proteinTarget - (d.proteinLogged ?? 0)));
    lines.push(`Protein: ${Math.round(d.proteinLogged ?? 0)}g of ${Math.round(d.proteinTarget)}g target (${gap}g to go)`);
  } else if (d.proteinLogged != null) {
    lines.push(`Protein: ${Math.round(d.proteinLogged)}g logged`);
  }
  if (d.carbsLogged != null) lines.push(`Carbs: ${Math.round(d.carbsLogged)}g`);
  if (d.fatLogged != null) lines.push(`Fat: ${Math.round(d.fatLogged)}g`);
  if (d.steps != null) lines.push(`Steps: ${d.steps}`);
  if (d.waterMl != null) lines.push(`Water: ${(d.waterMl / 1000).toFixed(1)}L`);
  if (d.latestWeight != null) lines.push(`Weight: ${d.latestWeight}kg`);
  if (d.weightTrend) lines.push(`Weight trend: ${d.weightTrend}`);
  if (d.streak != null && d.streak > 0) lines.push(`Logging streak: ${d.streak} days`);
  if (d.mealCount != null) lines.push(`Meals logged today: ${d.mealCount}`);

  if (lines.length === 0) {
    return 'The user has no data logged yet today. Give a short, welcoming nudge to log their first meal or weight.';
  }
  return `Here are my numbers for today:\n${lines.join('\n')}\n\nGive me one short coaching line.`;
}

export default async function handler(
  req: { method?: string; body?: unknown },
  res: {
    status: (code: number) => {
      json: (body: unknown) => void;
      end: () => void;
    };
    setHeader: (name: string, value: string) => void;
  },
): Promise<void> {
  res.setHeader('Cache-Control', 'no-store');

  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    res.status(500).json({ error: 'Coaching is not configured. Set ANTHROPIC_API_KEY in your Vercel project.' });
    return;
  }

  let data: CoachRequest;
  try {
    data = typeof req.body === 'string' ? JSON.parse(req.body) : (req.body as CoachRequest) ?? {};
  } catch {
    res.status(400).json({ error: 'Invalid JSON body' });
    return;
  }

  try {
    const client = new Anthropic();
    const message = await client.messages.create({
      model: 'claude-haiku-4-5',
      max_tokens: 200,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: buildUserMessage(data) }],
    });

    const insight = message.content
      .filter((block): block is Anthropic.TextBlock => block.type === 'text')
      .map(block => block.text)
      .join('')
      .trim();

    res.status(200).json({ insight });
  } catch (error) {
    const status = error instanceof Anthropic.APIError ? error.status ?? 502 : 502;
    res.status(status).json({ error: 'Could not generate a coaching insight right now.' });
  }
}
